### ISSUE TITLE
Java binding missing in 2.0.x 

### ISSUE THREAD

**Issue by ashishgupta02** [dnp3/opendnp3#111]
I am using the following steps to build dnp3 2.0.x on Linux operating systems:
$ export ASIO_HOME=${ASIO_DIR}/include
$ autoreconf -i -f
$ ./configure --prefix=${Install_Dir} --with-java=javac
$ make -j 4
$ make check -j 4
$ ./dnp3test <all pass>
$ ./openpaltest <all pass>
$ make install

Does not build java bindings ?

$ cd java
$ mvn install
# 

java.lang.UnsatisfiedLinkError: no opendnp3java in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at com.automatak.dnp3.impl.DNP3ManagerFactory.<clinit>(DNP3ManagerFactory.java:46)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite$$anonfun$fixture$1.apply$mcVI$sp(DNP3ManagerTestSuite.scala:18)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:142)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.fixture(DNP3ManagerTestSuite.scala:17)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite$$anonfun$1.apply$mcV$sp(DNP3ManagerTestSuite.scala:78)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite$$anonfun$1.apply(DNP3ManagerTestSuite.scala:78)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite$$anonfun$1.apply(DNP3ManagerTestSuite.scala:78)
    at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
    at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.withFixture(DNP3ManagerTestSuite.scala:11)
    at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
    at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
    at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
    at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.runTest(DNP3ManagerTestSuite.scala:11)
    at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
    at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
    at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
    at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
    at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.runTests(DNP3ManagerTestSuite.scala:11)
    at org.scalatest.Suite$class.run(Suite.scala:2303)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.org$scalatest$FunSuite$$super$run(DNP3ManagerTestSuite.scala:11)
    at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
    at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
    at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
    at com.automatak.dnp3.impl.DNP3ManagerTestSuite.run(DNP3ManagerTestSuite.scala:11)
    at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Tests in error: 
  com.automatak.dnp3.impl.DNP3ManagerTestSuite: no opendnp3java in java.library.path

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] opendnp3 .......................................... SUCCESS [1.592s]
[INFO] opendnp3-api ...................................... SUCCESS [4.697s]
[INFO] opendnp3-bindings ................................. FAILURE [0.830s]
[INFO] opendnp3-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.623s
[INFO] Finished at: Wed Dec 10 14:22:50 EST 2014
[INFO] Final Memory: 31M/351M
[INFO] ------------------------------------------------------------------------

**Comment by jadamcrain** [comment]
Java bindings are not supported in 2.0.x. I am currently looking for a customer that can fund porting this from 1.1.x to 2.0.x.

**Comment by ashishgupta02** [comment]
Is Java and DotNet bindings a significant effort in 2.0.x. compared to 1.1.x . What benefits does 2.0.x brings compared to 1.1.x release.

**Comment by jadamcrain** [comment]
.NET bindings are in 2.0.x.  Java is a fairly big effort b/c JNI is hard to work with.

Checkout the 2.0.x changelog here:

https://github.com/automatak/dnp3/blob/2.0.x/CHANGELOG.markdown

The biggest difference is that 1.1.x is legacy and won't receive any new features. For instance, we're starting to add DNP3 secure auth to 2.0.x but this will never make it into 1.1.x.

**Comment by ashishgupta02** [comment]
Thanks for your quick response. Currently I am evaluating its suitability for use in our products.

**Comment by jadamcrain** [comment]
2.0.x is a big step up in terms of quality and testing.

If you have more specific questions, please post to the mailing list:

http://groups.google.com/group/automatak-dnp3
