### ISSUE TITLE
Segfault when calling MasterAdaptor.Disable() or MasterAdaptor.Shutdown()

### ISSUE THREAD

**Issue by damonsensus** [dnp3/opendnp3#121]
I started following the references to determine what the issue is exactly.  Not being familiar with the code, it might take some time, so I am posting this in the meantime.

I built from 2.0.x following the most recent release (2.0.1.1 based on the CLRInterface AssemblyInfo).

{System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Automatak.DNP3.Adapter.MasterAdapter.Disable()
   at Sensus.DA.ScadaMaster.Dnp3.Outstation.Disconnect() in c:\develop\Sensus.DA.ScadaMaster\Sensus.DA.ScadaMaster\Dnp3\Outstation.cs:line 247
   at Sensus.DA.ScadaMaster.Dnp3.ChannelManager.InitChannel(ChannelCfg cfg) in 
... (elided as not relevant) ...
}

**Comment by jadamcrain** [comment]
Ok. Can you forward this to the list? We'll discuss there.

**Comment by jadamcrain** [comment]
Closing. Down the road we might might these calls idempotent.
